/**
 * Personal access tokens CRUD (D.1 of #731 Tier D).
 *
 * Extends dependency-upgrade-smoke.spec.ts:418-448 (vuelidate empty-name
 * branch only) into the full create + one-time-show + revoke contract:
 *
 *   /settings/api → empty-state paragraph rendered → "Create New Token" →
 *   fill name → submit → first modal closes → access-token modal opens
 *   with the plain bearer value in a <pre><code> → close modal → row
 *   appears in the tokens table → click "Delete" → row disappears and
 *   the empty-state paragraph returns.
 *
 * Isolation: fresh user. The seeded admin account accumulates tokens
 * across smoke runs (the smoke vuelidate test creates none, but earlier
 * iterations + dev usage may), so the empty-state-at-start and
 * empty-state-after-revoke assertions only hold against a freshly minted
 * user.
 *
 * The plain token is generated by laravel-passport as a JWT-style
 * accessToken — assert non-empty length rather than a regex on shape
 * (Passport's JWT prefix changes between key/cert configs; the contract
 * the user sees is "a long opaque string they copy once").
 */

import { test, expect } from '../support/console-gate';
import { loginAsFreshUser } from '../support/auth';

test.describe('Monica v4 — personal access tokens CRUD', () => {
  test('create token surfaces plain bearer once, revoke removes the row', async ({ page, consoleGate }) => {
    await loginAsFreshUser(page);
    await page.goto('/settings/api');

    // Empty-state paragraph (v-if="tokens.length === 0" in
    // PersonalAccessTokens.vue:29). Anchors the "before" state.
    await expect(
      page.getByText('You have not created any personal access tokens.'),
    ).toBeVisible();

    const tokenName = `pat-${Date.now()}`;

    // -- Create: open modal, fill name, submit.
    await page.getByRole('link', { name: 'Create New Token' }).click();

    const createModal = page.locator('.monica-modal__panel').filter({ hasText: 'Create Token' });
    await expect(createModal).toBeVisible();
    // form-input wires the HTML name attribute from its :id prop, not from a
    // bare "name" — so the input is name="create-token-name" not name="name".
    // Targeting by label keeps the spec independent of that detail.
    await createModal.getByLabel('Token name').fill(tokenName);
    await createModal.getByRole('link', { name: 'Create', exact: true }).click();
    await expect(createModal).toBeHidden();

    // -- One-time-show: access token modal opens. Filter on the help text
    // (api_token_help) — "Personal Access Tokens" alone also matches the
    // inline <em> in the populated-list table heading, so help text is the
    // unambiguous handle.
    const tokenModal = page
      .locator('.monica-modal__panel')
      .filter({ hasText: 'Here is your new personal access token' });
    await expect(tokenModal).toBeVisible();

    const accessToken = (await tokenModal.locator('pre code').textContent())?.trim() ?? '';
    // Passport JWTs are >>40 chars; assert long-opaque-string rather than
    // shape so a config change in the keypair doesn't false-positive.
    expect(accessToken.length).toBeGreaterThan(40);

    // Reload to dismiss the modal and pick up the persisted token from
    // the server. The footer "Close" button is wired to closeModal() which
    // calls $refs.form.reset() — but $refs.form was unmounted when the
    // create modal closed, so closeModal throws before the boolean reset
    // ever runs (vue 2 → 3 unmount-ordering footgun; see #771). Reload
    // sidesteps the broken control AND gives a stronger assertion: the
    // row is present because the token round-tripped to the database,
    // not because of local-array push() from the create response.
    await page.reload();

    // -- List: the new token row renders with its name + a Delete action.
    const row = page.locator('.dt-row', { hasText: tokenName });
    await expect(row).toBeVisible();

    // -- Revoke: click the row's Delete span; revoke() refreshes tokens
    // via getTokens() which collapses the populated table v-else and
    // re-renders the v-if empty-state paragraph.
    await row.getByText('Delete', { exact: true }).click();
    await expect(page.locator('.dt-row', { hasText: tokenName })).toHaveCount(0);
    await expect(
      page.getByText('You have not created any personal access tokens.'),
    ).toBeVisible();

    consoleGate.assertNoUnknownErrors('/settings/api (PAT create + revoke)');
  });
});
